pipeline{
    agent none
    stages{
        stage('Java app - Backend'){
            agent{
                docker {image 'openjdk:24-slim'}
            }
            steps{
                sh 'ls -l'
                sh 'ls -l helloWorld.java'
                sh 'cp multi-stage-simple-java-node-program/helloWorld.java /tmp/helloWorld.java'
                sh 'javac /tmp/helloWorld.java'
                sh 'java /tmp/helloWorld'
            }
            
        }
        stage('Node - Frontend'){
            agent{
                docker {image 'node:slim'}
            }
            steps{
                sh 'ls -l frontend.js'
                sh 'cp multi-stage-simple-java-node-program/frontend.js /tmp/frontend.js'
                sh 'node /tmp/frontend.js'
            }
        }
    }
}